version: '3.8'

services:
  app:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_NAMESPACE:-kkape}/supabase-login-ui:${APP_VERSION:-latest}
    container_name: supabase-login-ui
    ports:
      - "${PORT:-3110}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_PUBLIC_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
      - NEXT_PUBLIC_SITE_URL=${SITE_URL}
      - NEXT_PUBLIC_AUTH_GITHUB_ENABLED=${GOTRUE_EXTERNAL_GITHUB_ENABLED:-false}
      - NEXT_PUBLIC_AUTH_GOOGLE_ENABLED=${GOTRUE_EXTERNAL_GOOGLE_ENABLED:-false}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - TZ=${TZ:-Asia/Shanghai}
    restart: always
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - supabase-network
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-1}'
          memory: ${MEMORY_LIMIT:-512M}
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  supabase-network:
    name: supabase-network
    driver: bridge