version: '3'

services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_PUBLIC_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
        - NEXT_PUBLIC_SITE_URL=${SITE_URL}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_PUBLIC_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
      - NEXT_PUBLIC_SITE_URL=${SITE_URL}
      - NEXT_PUBLIC_AUTH_GITHUB_ENABLED=${GOTRUE_EXTERNAL_GITHUB_ENABLED}
      - NEXT_PUBLIC_AUTH_GOOGLE_ENABLED=${GOTRUE_EXTERNAL_GOOGLE_ENABLED}
    restart: always